name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build and run test
      run: |
        cd c++/utils
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        Release/test.out
